# Generated by Django 4.0.5 on 2024-04-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_nonitasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonitasset',
            name='asset_type',
            field=models.CharField(blank=True, default='NON IT Assets', max_length=50),
        ),
    ]
